### ISSUE TITLE
Branch dev não está compilando

### ISSUE THREAD

**Issue by gabrielvcunha** [ekalmentero/frameworkufrrj#18]
```
modules.export = tabelas;
^
ReferenceError: modules is not defined
    at Object.<anonymous> (C:\Users\gabri\Work\frameworkufrrj\tabelas.js:8:1)
    at Module._compile (module.js:624:30)
    at babelWatchLoader (C:\Users\gabri\Work\frameworkufrrj\node_modules\babel-watch\runner.js:50:13)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\gabri\Work\frameworkufrrj\node_modules\babel-watch\runner.js:61:7)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\gabri\Work\frameworkufrrj\BD.js:2:15)

**Comment by gabrielvcunha** [comment]
Resolvido.
